/**
 * ----------------------------------
 * DOCUMENTATION GENERATED BY COPILOT
 * ----------------------------------
 * script.js - Memory Game Logic
 *
 * This file contains the main JavaScript logic for the memory game (muistipeli).
 * It handles board creation, user interactions, game state management, and UI updates.
 *
 * Main Features:
 * - Dynamically generates the game board based on user selection.
 * - Handles card flipping and matching logic.
 * - Tracks and displays the player's progress and score.
 * - Provides functions to reset or restart the game.
 *
 * Key Functions:
 * - createBoard(): Generates the game board and initializes game state.
 * - handleCardClick(event): Handles user clicks on cards, manages flipping and matching.
 * - shuffleNames(nameList): Utility function to randomize the order of cards.
 * - resetGame(): Resets the game state and UI for a new game.
 *
 * Dependencies:
 * - Assumes the presence of specific HTML elements (e.g., table cells, score display).
 * - Uses standard DOM APIs.
 *
 * Usage:
 * - Include this script in your HTML file.
 * - Ensure the DOM is fully loaded before calling createBoard().
 *
 * Author: [Your Name]
 * Date: [Date]
 */

/*TODO:
 *
 * handle matching logic and disabling matched images
 * track number of guesses
 * display score and timer
 */

var board;
var clickedOnce = false;
var created = false;
var gameSizeRows, gameSizeCols;
var running = false;
var guesses;

function onClickPicture() {
  let img = this.querySelector("img");
  let oldAlt = img.alt;
  let oldSrc = img.src;
  img.alt = oldSrc;
  img.src = oldAlt
}

function resetGame() {
  if (!running) { return; }
  created = false;
  running = false;
  guesses = 0;
  board = [];
  document.querySelectorAll("td").forEach((e) => e.remove());
}

function setGameSize() {
  let sizes = document.getElementById("sizeSelect").value.split("x");
  gameSizeRows = parseInt(sizes[0]);
  gameSizeCols = parseInt(sizes[1]);
  createBoard();
}

function startGame() {
  if (running) {
    alert("Game already running! Please reset before starting a new game.");
    return;
  }
  guesses = 0;
  running = true;
}

function shuffleNames(nameList) {
  for (let i = nameList.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [nameList[i], nameList[j]] = [nameList[j], nameList[i]];
  }
  return nameList;
}

function createBoard() {

  if (created) { return; }

  let filenames = []
  let gridSize = (gameSizeRows * gameSizeCols) / 2;

  for (let i = 1; i <= gridSize; i++) {
    filenames.push("dev" + i + ".jpg");
    filenames.push("dev" + i + ".jpg");
  }

  filenames = shuffleNames(filenames);
  console.log(filenames);

  let pictureIdAppendix = 1;
  let filenameSuffixIdx = 0;

  for (let i = 1; i <= gameSizeRows; i++) {
    let newTr = document.createElement("tr");
    newTr.setAttribute("id", "row" + i);

    for (let j = 1; j <= gameSizeCols; j++) {
      //create new td element
      let newTd = document.createElement("td");
      newTd.setAttribute("id", "pic" + pictureIdAppendix);
      newTd.addEventListener("click", onClickPicture);
      //create img element, assign filepath and id and append to new td
      let img = document.createElement("img");
      img.alt = "./resources/img/dev_icons/" + filenames[filenameSuffixIdx];
      img.src = "./resources/img/dev_icons/devdefault.jpg"
      img.id = filenames[filenameSuffixIdx];
      newTd.appendChild(img);
      pictureIdAppendix++;

      filenameSuffixIdx++;

      if (filenameSuffixIdx == gameSizeRows * gameSizeCols) {
        filenameSuffixIdx = 1;
      }
      newTr.appendChild(newTd);
    }
    let boardContainer = document.getElementById("boardContainer");
    boardContainer.appendChild(newTr);
  }
  board = boardContainer;
  created = true;
}
