/**
 * DOCUMENTATION GENERATED BY COPILOT
 *
 * Memory Game Script
 *
 * This script implements a memory matching game with the following features:
 *
 * Game State Variables:
 * - board: Reference to the game board container element.
 * - created: Boolean indicating if the board has been created.
 * - gameSizeRows, gameSizeCols: Number of rows and columns for the game board.
 * - running: Boolean indicating if the game is currently running.
 * - guesses: Number of guesses made by the player.
 * - previousImg, clickedImg: References to previously and currently clicked image elements.
 * - previousContainer, clickedContainer: References to previously and currently clicked container elements.
 * - processing: Boolean to prevent actions during animations.
 * - timerInterval: Interval ID for the game timer.
 * - startTime: Timestamp when the game started.
 *
 * Functions:
 * - onClickPicture(): Handles click events on picture containers, reveals images, checks for matches,
 *   and updates guess count.
 * - resetState(): Resets references after a guess, allowing further interaction.
 * - resetGame(): Resets the game state, stops the timer, and clears the board.
 * - setGameSize(): Sets the board size based on user selection.
 * - startGame(): Starts a new game, initializes the timer, and creates the board.
 * - shuffleNames(nameList): Shuffles an array of image filenames using the Fisher-Yates algorithm.
 * - gameTimer(): Updates the timer display, showing elapsed time in mm:ss:cc format.
 * - stopTimer(): Stops the timer and resets the timer display.
 * - createBoard(): Creates the game board with shuffled image pairs, sets up the grid, and attaches click handlers.
 *
 * Usage:
 * - Call setGameSize() to set the desired board size.
 * - Call startGame() to begin a new game.
 * - Use resetGame() to reset the game at any time.
 *
 * The timer starts from 00:00:00 and displays minutes, seconds, and hundredths of a second.
 */

var created = false;
var gameSizeRows, gameSizeCols;
var running = false;
var guesses = 0;
var previousImg = null;
var clickedImg = null;
var clickedContainer = null;
var previousContainer = null;
var processing = false;
var timerInterval = null;
var startTime = null;

function onClickPicture() {
	if (!running) return;
	if (processing) return;
	if (this === previousContainer) return;
	if (!previousImg) {
		previousContainer = this;
		previousImg = this.querySelector("img");
		previousImg.style.display = "inline";
		return;
	} else {
		clickedContainer = this;
		clickedImg = this.querySelector("img");
		clickedImg.style.display = "inline";
		if (previousImg.src === clickedImg.src) {
			previousContainer.removeEventListener("click", onClickPicture);
			clickedContainer.removeEventListener("click", onClickPicture);
			resetState();
		} else {
			processing = true;
			setTimeout(() => {
				previousImg.style.display = "none";
				clickedImg.style.display = "none";
				resetState();
			}, 1000);
		}
		guesses++;
		document.querySelector("#arvaukset").innerText =
			`Arvausten määrä: ${guesses}`;
	}
}

function resetState() {
	processing = false;
	previousImg = null;
	clickedImg = null;
	previousContainer = null;
	clickedContainer = null;
}

function resetGame() {
	stopTimer();
	created = false;
	running = false;
	guesses = 0;
	board = [];
	document.querySelectorAll(".gridCell").forEach((e) => e.remove());
}

function setGameSize() {
	let sizes = document.getElementById("sizeSelect").value.split("x");
	gameSizeRows = parseInt(sizes[0]);
	gameSizeCols = parseInt(sizes[1]);
	createBoard();
}

function startGame() {
	if (running) {
		alert("Game already running! Please reset before starting a new game.");
		return;
	}
	startTime = Date.now();
	timerInterval = setInterval(gameTimer, 10);
	running = true;
}

function shuffleNames(nameList) {
	for (let i = nameList.length - 1; i > 0; i--) {
		const j = Math.floor(Math.random() * (i + 1));
		[nameList[i], nameList[j]] = [nameList[j], nameList[i]];
	}
	return nameList;
}

function gameTimer() {
	const elapsed = Date.now() - startTime;
	const minutes = Math.floor(elapsed / 60000);
	const seconds = Math.floor((elapsed % 60000) / 1000);
	const centiseconds = Math.floor((elapsed % 1000) / 10);
	document.getElementById("aika").innerHTML =
		`Aika: ${minutes}:${seconds.toString().padStart(2, "0")}:${centiseconds.toString().padStart(2, "0")}`;
}

function stopTimer() {
	clearInterval(timerInterval);
	document.getElementById("aika").innerHTML = "00:00:00";
}

function createBoard() {
	if (created) {
		return;
	}
	let filenames = [];
	let gridSize = (gameSizeRows * gameSizeCols) / 2;

	for (let i = 1; i <= gridSize; i++) {
		filenames.push("dev" + i + ".jpg");
		filenames.push("dev" + i + ".jpg");
	}

	filenames = shuffleNames(filenames);

	let filenameSuffixIdx = 0;

	const board = document.getElementById("boardContainer");
	board.style.gridTemplateRows = `repeat(${gameSizeRows}, 1fr)`;
	board.style.gridTemplateColumns = `repeat(${gameSizeCols}, 1fr)`;
	board.innerHTML = "";

	for (let i = 1; i <= gameSizeCols * gameSizeRows; i++) {
		let gridCell = document.createElement("div");
		gridCell.style.backgroundImage =
			"url(./resources/img/dev_icons/devdefault.jpg)";
		gridCell.id = "pic" + i;
		gridCell.className = "gridCell";
		gridCell.addEventListener("click", onClickPicture);

		let img = document.createElement("img");
		img.src = "./resources/img/dev_icons/" + filenames[filenameSuffixIdx];
		img.id = filenames[filenameSuffixIdx];
		img.style.display = "none";

		console.log(filenameSuffixIdx);
		gridCell.appendChild(img);
		board.appendChild(gridCell);
		filenameSuffixIdx++;
	}
	board.width = gameSizeRows * 100 + gameSizeRows * 6 + "px";
	board.height = gameSizeCols * 100 + gameSizeCols * 6 + "px";
	created = true;
}
